### ISSUE TITLE
Is the module maintained?

### ISSUE THREAD

**Issue by hj-collab** [zhangjiayin/caddy-mysql-storage#1]
Hello, Thank you for the module. Is it maintained?

**Comment by zhangjiayin** [comment]
Hello, thank you for your interest. 
Yes, this module is still being maintained. 
If you have any questions or suggestions, feel free to raise them at any time.

**Comment by himanshu-mahendra-jain** [comment]
Hi @zhangjiayin,

Thanks for your prompt response. I'll test it out and share my feedback. 

Best regards,

**Comment by zhangjiayin** [comment]
it is so long time.
I'll close this issue.
