### ISSUE TITLE
Is MySQL router supported?

### ISSUE THREAD

**Issue by jb-home** [zhangjiayin/caddy-mysql-storage#2]
Hi,

I am using a high availability MySQL cluster with three machines.
For my other applications I am using the MySQL Router to connect to the databases.

As soon as I specify the MySQL Router in the Caddyfile I am getting 'i/o timeout'

Caddyfile configuration:
```
{
	storage mysql {
		dsn "user:pw@tcp(mysql-router-service.caddy-test.svc.cluster.local:6446)/caddy-test?charset=utf8mb4"
	}
}
```

**Comment by zhangjiayin** [comment]
Hi, could you try  these command?

```
ping mysql-router-service.caddy-test.svc.cluster.local
nc -v mysql-router-service.caddy-test.svc.cluster.local 6446
```
and can you run the mysql client  to verify the configuration
```
mysql -hmysql-router-service.caddy-test.svc.cluster.local -P6446 -uuser -p
```

**Comment by jb-home** [comment]
Hi,

the mysql-router works fine. I tested it and it is working with other applications in the same configuration.

I also tried to map the mysql-router to port 3306 to make sure the it is not a port number issue.
I think the communication with a mysql-router is slightly different than direct mysql communication.
Have you been able to reproduce this issue?
Thanks for taking a look at this!

**Comment by zhangjiayin** [comment]
hi
I have tested with MySQL  5.7.37, MySQL Router 8.0.28 ,
and mysql port is 3306 and mysql router port is 7001,7002 and the configuration for mysql router just like 
<img width="300" alt="image" src="https://github.com/zhangjiayin/caddy-mysql-storage/assets/806446/36539ae7-968a-4dc5-a597-f8ff72f344a4">

and caddy  works well.
<img width="684" alt="image" src="https://github.com/zhangjiayin/caddy-mysql-storage/assets/806446/30a1afc2-d17a-4b38-9c72-a587f476dbf8">
<img width="1128" alt="image" src="https://github.com/zhangjiayin/caddy-mysql-storage/assets/806446/03d6e9ff-c649-487b-bdf3-ac33ea7f4574">

 because you got 'i/o timeout'
So  I guess it should something wrong with your  configuration or the network is not connectable.
could you provide Further information for it 
For example  the result for these command?
```
ping mysql-router-service.caddy-test.svc.cluster.local
nc -v mysql-router-service.caddy-test.svc.cluster.local 6446
```
and can you run the mysql client to verify the configuration
```
mysql -hmysql-router-service.caddy-test.svc.cluster.local -P6446 -uuser -p
```

**Comment by jb-home** [comment]
Which protocol are you using?
For me default port 6446 is the classic protocol.
Are you using the X protocol that would be default port 6448.
I will test this on monday...

Thanks again for your efforts!

**Comment by zhangjiayin** [comment]
For  classic protocol it works well
For. X protocol  it should got the error
```
Error: loading initial config: loading new config: creating storage value: context deadline exceeded
```
This repo use  https://github.com/go-sql-driver/mysql support mysql connections ,it seems did not support x protocol

**Comment by jb-home** [comment]
I found the issue...
As soon as I use an IP in the dsn it works perfectly.
```
{
	storage mysql {
		dsn "user:pw@tcp(172.19.131.86:6446)/caddy-test?charset=utf8mb4"
	}
}
```

When I use a hostname or FQDN and the hostname (NETBIOS) is longer than 15 characters it stops working and results in 'i/o timeout'.

Example 16 Charatcter hostname: (fails)
```
{
	storage mysql {
		dsn "user:pw@tcp(mysql-router-svc.caddy-test.svc.cluster.local:6446)/caddy-test?charset=utf8mb4"
	}
}
```

Example 15 character hostname: (works)
```
{
	storage mysql {
		dsn "user:pw@tcp(mysql-routersvc.caddy-test.svc.cluster.local:6446)/caddy-test?charset=utf8mb4"
	}
}
```

Is there anything you can do to fix that? Or is it an issue in an external module?

**Comment by zhangjiayin** [comment]
hi 
 the long  hostname:mysql-router-service.caddy-test.svc.cluster.local   is works fine when I test it (add 127.0.0.1 mysql-router-service.caddy-test.svc.cluster.local to my hosts)
<img width="1379" alt="image" src="https://github.com/zhangjiayin/caddy-mysql-storage/assets/806446/39fa9bbf-1f71-4a6d-8d8b-dddd363a2157">
it may be an issue  on you system , could you try ping in your terminal? 
```
ping mysql-router-service.caddy-test.svc.cluster.local
```

**Comment by zhangjiayin** [comment]
For the description "15 character limitation", it seem a  limitation for Windows/NetBIOS (https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou),
<img width="866" alt="image" src="https://github.com/zhangjiayin/caddy-mysql-storage/assets/806446/11d28cb3-2f4f-48b5-813c-87c773c8f9a0">


to resolve it 

1、could you replace the name binding with  DNS or  hosts
2、just shorten it  simply.

**Comment by jb-home** [comment]
I resolved it by shortening the hostname to 15 characters.
Thanks for your support!

**Comment by jb-home** [comment]
I resolved it by shortening the hostname to 15 characters.
Thanks for your support!
